book_free_hours:
  fields:
    start:
      required: true
      example: "2026-10-31 09:00:00"
      selector:
        datetime:
    hours:
      default: 1
      selector:
        number:
          min: 1
          max: 15
          mode: box
    config_entry_id:
      selector:
        config_entry:
          integration: edf_weekend_saver

cancel_free_hours:
  fields:
    start:
      required: true
      example: "2026-10-31 09:00:00"
      selector:
        datetime:
    hours:
      default: 1
      selector:
        number:
          min: 1
          max: 15
          mode: box
    config_entry_id:
      selector:
        config_entry:
          integration: edf_weekend_saver
